---
title: "MBA 6693 Business Analytics"
author: 'Name: Vinayak B. Menon'
date: "11/07/2020"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
subtitle: 'Assignment 1: Regression Models' 
---

\textbf{Objective:}\

This report aims to study the significance of location when considering the number of sales of child car seats, based on the Carseats data in R. Our analysis will focus on where the most car seats number are sold based on whether the store location is in the US or abroad. We will also consider a classification based on urban or rural locations. By the end of this study, we aim to establish whether or not there is any significance in store location, and if so, where it significance lies most, with respect to the number of child car seats.\

We will first explore the Carseats dataset provided, which would include cleaning the data and establishing any patterns through graphical tools. We then proceed to create a multivariate regression model using all the factors included, and study the efficiency of the model. To reduce the complexity and strengthen the model, we will perform a backward step regression. Finally we compare all considered models in terms of their explanatory power and fit, and check how much the location variables influence the number of car seats that are sold at the store.\

\textbf{Data Exploration:}\